ARG ELK_VERSION

# https://github.com/elastic/logstash-docker
# FROM docker.elastic.co/logstash/logstash-oss:${ELK_VERSION}
FROM registry-vpc.cn-hangzhou.aliyuncs.com/dm-maker/elk-logstash-oss:${ELK_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
